server:
  port: 8080

spring:
  application:
    name: nebula-commerce
  # ⚡ 开启 Java 21 虚拟线程
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/nebula_commerce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASSWORD:GCYgcygcygcy123/} # 请修改密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境开启SQL日志

# 自定义 JWT 配置
jwt:
  secret: ${JWT_SECRET:NebulaCommerceSecretKeyForDevelopmentPhase2026!}
  expiration-millis: ${JWT_EXPIRATION_MILLIS:86400000}
